name = "absensi-online"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "absensi-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Replace with your D1 database ID
